server:
  port: 8080

service:
  message: API Gateway loaded from Github config repo

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      routes:

        # =========================
        # Product Service
        # =========================
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products,/api/v1/products/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - AddResponseHeader=X-Platform, microservices-pro

        # =========================
        # Inventory Service
        # =========================
        - id: inventory-service-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory,/api/v1/inventory/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - AddResponseHeader=X-Platform, microservices-pro

        # =========================
        # Order Service
        # =========================
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/orders,/api/orders/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - AddResponseHeader=X-Platform, microservices-pro

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-for-jwt-authentication-123456}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoint:
    gateway:
      access: read-only

  endpoints:
    web:
      exposure:
        include: health,info,gateway