server:
  port: 8080

service:
  message: API Gateway loaded from Github config repo

spring:
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/products,/api/products/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - StripPrefix=1
            - AddResponseHeader=X-Platform, microservices-pro
        - id: inventory-service-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory,/api/inventory/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - StripPrefix=1
            - AddResponseHeader=X-Platform, microservices-pro
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/orders,/api/orders/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - StripPrefix=1
            - AddResponseHeader=X-Platform, microservices-pro

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-for-jwt-authentication-123456}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    gateway:
      access: read-only
  endpoints:
    web:
      exposure:
        include: health,info,gateway
