server:
  port: 8080

service:
  message: API Gateway2 loaded from Github config repo

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service-route
              uri: lb://product-service
              predicates:
                - Path=/api/products/**
              filters:
                - StripPrefix=1

            - id: inventory-service-route
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventory/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway